name: Node.js CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: h5p-interactive-board

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build Interactive Board
        run: |
          cd h5p-interactive-board
          npm ci
          npm run build

      - name: Get and build dependencies
        run: |
          COLOR_BLUE='\033[0;34m'

          mkdir -p dist
          cd dist

          # Clone dependencies
          echo -e "${COLOR_BLUE}Cloning dependencies${COLOR_OFF}"
          while read -r repo; do git clone ${repo}; done < ../h5p-interactive-board/build_info/repos

          # Build distribution versions
          echo -e "${COLOR_BLUE}Building dependencies${COLOR_OFF}"
          for dir in */ ; do
            if [ -d "$dir" ]; then
              if [ "$(basename $dir") == "h5p-true-false" ]; then
                continue # Skip h5p-true-false, as it has no build script
              fi

              pushd $dir
              echo -e "${COLOR_BLUE}Building $dir${COLOR_OFF}"
              if [ test -f "package.json" ]; then
                npm ci
                npm run build
              fi
              popd
            fi
          done

          cp -r ../h5p-interactive-board .
      - run: |
          cd dist
          ls
          npm install -g h5p
          h5p pack -r h5p-interactive-board h5p-editor-interactive-board interactive-board.h5p
          h5p validate interactive-board.h5p

      - name: Store packed H5P as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: interactive-board.h5p
          path: dist/interactive-board.h5p

      - name: Load library.json
        id: set_library
        run: |
          ls
          JSON=$(cat ./h5p-interactive-board/library.json)
          JSON="${JSON//'%'/%25}"
          JSON="${JSON//$'\n'/%0A}"
          JSON="${JSON//$'\r'/%0D}"
          echo "::set-output name=library::${JSON}"
      - uses: 'marvinpinto/action-automatic-releases@latest' # https://github.com/marvinpinto/actions/tree/master/packages/automatic-releases
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: |
            ${{
              format(
                'v{0}.{1}.{2}',
                fromJson(steps.set_library.outputs.library).majorVersion,
                fromJson(steps.set_library.outputs.library).minorVersion,
                fromJson(steps.set_library.outputs.library).patchVersion
              )
            }}
          prerelease: false
          files: |
            dist/interactive-board.h5p
